# Generated by Django 6.0.6 on 2026-07-13 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_alter_product_category_alter_product_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Skin Care', 'Skin Care'), ('Body Care', 'Body Care'), ('Lip Care', 'Lip Care'), ('General Goods', 'General Goods'), ('Beauty tools and Accessories', 'Beauty tools and Accessories'), ('Oral Care', 'Oral Care'), ('Combo', 'Combo'), ('Glow Box', 'Glow Box'), ('Care Box', 'Care Box'), ('Birthday Package', 'Birthday Package')], max_length=100),
        ),
    ]
