# Generated by Django 6.0.6 on 2026-07-21 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_product_color_1_product_color_2_product_color_3_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='stock_large',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='stock_medium',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='stock_small',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='product',
            name='has_size_options',
            field=models.BooleanField(default=False, help_text='Check this to offer Large, Medium, and Small sizes.'),
        ),
    ]
