# Generated by Django 6.0.6 on 2026-07-23 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_product_stock_large_product_stock_medium_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='original_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='If set higher than the price, it will show a SALE badge and crossed-out old price', max_digits=10, max_length=10, null=True),
        ),
    ]
