# Generated by Django 6.0.6 on 2026-07-24 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_orderitem_color_orderitem_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='color_4',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='color_5',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
